name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy Frontend Production
    runs-on: [self-hosted, Production]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and build
        run: |
          npm install
          npm run build -- --mode production
          ls -la dist

      - name: Sync build to VPS production folder
        run: |
          sudo rm -rf /opt/apps/frontend-production/*
          sudo cp -a dist/. /opt/apps/frontend-production/

      - name: Restart nginx
        run: sudo service nginx restart
